### ISSUE TITLE
Gather information about popular graph cutting algorithms and how we want to leverage them for our task.

### ISSUE THREAD

**Issue by lov435** [lov435/SoftwareImprovement#18]

**Comment by lov435** [comment]
This issue is a prerequisite for the issue number 16 where we have to select and implement a specific graph cutting algorithm to group the comments individually instead of grouping a pair of comments.

**Comment by damevski** [comment]
https://www.aclweb.org/anthology/J10-3004.pdf

Section 4.2 (although the entire article has a lot of useful things including metrics and considerations)

**Comment by damevski** [comment]
Closing this issue. Although, it could be used as a reference going forward.
