### ISSUE TITLE
Minor_3.1 Mention the proportion of answers with a threshold number (7) of comments

### ISSUE THREAD

**Issue by lov435** [lov435/SoftwareImprovement#42]
Comment 3.7: The results in the paper apply to the scenario when there is at least one hidden comment, or when there are at least two hidden comments. Although the rationale to choose a threshold of 7 makes sense, the paper should also mention the proportion of answers with such a threshold. If answers with a threshold of 7 comments form a small set among answers with hidden comments, the generalizability of the current study would be limited. Therefore, it is important to obtain this quantitative measure to help the audience better understand the impact of the scenario under study.

**Comment by lov435** [comment]
Ready for your review

**Comment by damevski** [comment]
Reviewed and closing
