### ISSUE TITLE
Minor_2.2.1 hyperparameter tuning for the Random Forest model

### ISSUE THREAD

**Issue by lov435** [lov435/SoftwareImprovement#45]
2.      Evaluation of the Random Forest Model (Section 5)

Parameter hypertuning. I am surprised to see that the authors did not use any hyperparameter tuning for the Random Forest model. I strongly suggest that this should be done both for the Random Forest model and for other shallow learning baselines.

**Comment by lov435** [comment]
**Editor's note**: "As for hyperparameter tuning (R2), I agree this is a recommended practice and should have been performed. Again, this point was only partially raised by the reviewer during the first round. As such I am not recommending this as a mandatory change. However, this issue must be at least discussed among the threats to validity."

**Comment by damevski** [comment]
Perhaps quickly explore a few parameters of random forest as part of #46. What do you think @lov435

**Comment by lov435** [comment]
@damevski, The issue #46 is for testing our model with XGBoost and LightGBM ensembles. I am not sure how this issue of hyperparameter turning of Random Forest is related to #46. But regardless of #45 and #46 are related or not, I can certainly add some more code to tune RF.

**Comment by damevski** [comment]
Addressed this. Please review @lov435

**Comment by lov435** [comment]
Reviewd. Looks good.
