### ISSUE TITLE
Minor_2.2.2 Improper baseline for the Random Forest model

### ISSUE THREAD

**Issue by lov435** [lov435/SoftwareImprovement#46]
2.      Evaluation of the Random Forest Model (Section 5)
Why the baselines of KNN, ANN, SVM are picked over others like XGBoost, LightGBM? Given Random Forest slightly outperforms the baselines, other the tree-based models seem like good candidates to also check. This needs to be addressed properly.

**Comment by damevski** [comment]
We should probably do this one

**Comment by lov435** [comment]
**LightGBM model**
Average cross validation F-measure is
0.7680840960419251
Average cross validation precision is
0.7696010743751179
Average cross validation recall is
0.6816296593186373

**XGBoost model**
Average cross validation F-measure is
0.7519264023754457
Average cross validation precision is
0.7394622968533169
Average cross validation recall is
0.6744244488977956

**Random Forest model**
Average cross validation F-measure is
0.7789988743522519
Average cross validation precision is
0.8007180943577371
Average cross validation recall is
0.6842376753507013

**Comment by lov435** [comment]
Hi @damevski, do we want to add the above results to our paper? Or is it okay if we just mention that we tried XGBoost and LightGBM along with RF and found that RF was giving slightly better results?

**Comment by damevski** [comment]
Yes, I am okay with this plan @lov435

**Comment by lov435** [comment]
Hello @damevski,

Based on our conversation on Friday,

1. I have updated the results section to include text on XGBoost and LightGBM.
2. However, I have NOT updated the Methodology section to remove excess text that we thought should have been in the Results section. I still feel that the way it currently reads is fine. If you don't mind, can you please re-read that Methodology section? If you still insist, I will remove one statement "we observed that Random Forest (number of estimators = 1, 500; max depth = 5) performed slightly better than the others. ". Please advise.

**Comment by damevski** [comment]
Done. Closing
