### ISSUE TITLE
Minor_2.2.4 Evaluate the model performance on survey data

### ISSUE THREAD

**Issue by lov435** [lov435/SoftwareImprovement#48]
2.      Evaluation of the Random Forest Model (Section 5)
In terms using a evaluation dataset separate from the survey data. Did your evaluation use the survey data at all? How about you report the results like this: train the model on your dataset of 11,822 comments and show its performance on the survey data. This is important, because the 11,822 comments are manually annotated by the two authors whereas the survey dataset is annotated by survey users. If the model performs well on the survey dataset, that should give an added confidence that the model is robust.

**Comment by damevski** [comment]
Problem is that the survey data has multiple levels of relatedness.

**Comment by damevski** [comment]
i don't think we do this.

**Comment by lov435** [comment]
i am not making any changes in the paper for this issue. I am just respoding to it in the response document stating the reason for no action being taken. Please review the answer in the response document and close this issue if it feels appropriate.

**Comment by damevski** [comment]
Done. Closing.
